import type { InoscConfig, TaskManifest } from '../types.ts'
import { activeLinks } from '../task/activeLinks.ts'

/** Renders the task-root AGENTS.md read by Cursor and Codex (and Claude Code via CLAUDE.md). */
export const renderAgentsMd = (config: InoscConfig, manifest: TaskManifest): string => {
  const names = manifest.repos.map((r) => r.name)
  const available = Object.keys(config.repos).filter((n) => !names.includes(n))
  const links = activeLinks(config.links, names)
  const lines: string[] = [
    `# Task ${manifest.id}`,
    '',
    'This folder is an inosc task workspace: one git worktree per repo, side by side, for this task only.',
    'Generated by inosc and rewritten on `inosc add`; change `inosc.json` in the workspace root instead of editing this file.',
    '',
    '## Repos',
    '',
    '| Repo | Path | Mode | Branch | Base |',
    '|---|---|---|---|---|',
    ...manifest.repos.map(
      (r) =>
        `| ${r.name} | \`${r.name}/\` | ${r.mode === 'edit' ? 'edit' : 'read-only'} | ${r.branch ? `\`${r.branch}\`` : 'detached'} | \`${r.base}\` |`,
    ),
  ]
  const described = manifest.repos.filter((r) => config.repos[r.name]?.description)
  if (described.length > 0) {
    lines.push('', ...described.map((r) => `- **${r.name}**: ${config.repos[r.name]?.description}`))
  }
  if (links.length > 0) {
    lines.push(
      '',
      '## Links',
      '',
      'Local-only dependency links between these worktrees. They are already applied; rerun if you reinstall.',
      '',
      ...links.map(
        (l) =>
          `- \`${l.from}\` uses \`${l.to}\` from this task: \`cd ${l.from} && ${l.run.replaceAll('{to}', `../${l.to}`)}\`${l.description ? ` (${l.description})` : ''}`,
      ),
    )
  }
  const withCommands = manifest.repos.filter((r) => Object.keys(config.repos[r.name]?.commands ?? {}).length > 0)
  if (withCommands.length > 0) {
    lines.push('', '## Commands', '', 'Run from inside the repo folder.')
    for (const r of withCommands) {
      lines.push('', `### ${r.name}`, '')
      for (const [k, v] of Object.entries(config.repos[r.name]?.commands ?? {})) lines.push(`- ${k}: \`${v}\``)
    }
  }
  lines.push(
    '',
    '## Rules',
    '',
    '- Only change repos in edit mode. Read-only repos are detached at their base for reference: do not commit there.',
    "- Each repo's own AGENTS.md / CLAUDE.md is authoritative inside that repo. Read it before working there.",
    '- Run git, package-manager and build commands from inside a repo folder, never from the task root.',
    '- Keep link changes local: never commit files a link step rewrites (for example a lockfile) unless asked.',
    `- Need another repo? \`inosc add ${manifest.id} <repo>\` (add \`--read <repo>\` for reference-only).${available.length > 0 ? ` Available: ${available.join(', ')}.` : ''}`,
    `- \`inosc done ${manifest.id}\` removes this folder; it refuses while anything is uncommitted or unpushed. Only the user runs it.`,
  )
  if (config.instructions.length > 0) lines.push('', '## Notes', '', ...config.instructions)
  return `${lines.join('\n')}\n`
}
